### ISSUE TITLE
Could you tag it and register on code.dlang.org?

### ISSUE THREAD

**Issue by drug007** [SFrijters/hdf5-d#2]
It would be very nice!

**Comment by SFrijters** [comment]
I am planning to add an update soon which will add support for OpenMPI in addition to the current hacky MPICH datatypes, I will tag / register as soon as I get that working. In future this code may also be replaced by or merged with https://github.com/Laeeth/d_hdf5, which is already registered for Dub.

**Comment by drug007** [comment]
I thinks your bindings is more comfortable than [d_hdf5](https://github.com/Laeeth/d_hdf5) because they are closer to original - they have the same directory structure at least and it's simpler to update theses bindings, I guess. Moreover I'm sure that bindings and wrappers should be different projects where wrappers depends on respective bindings.

**Comment by SFrijters** [comment]
Ok, I registered the code for now and raised some issues for myself to work on. I will also take a look at your PR then. I agree that plain bindings are nice to have, but I'm not sure if they should be a different project altogether. If a module that only has the bindings is present, that should make it modular enough, no?

**Comment by drug007** [comment]
Thank you!
I'm not sure I understand your question. I think that bindings and wrappers should be different project because then you have opportunity to make different wrappers using the same bindings. For example if I'll have enough time I'll make my own wrapper for hdf5 to experiment with it. Also bindings should be as close as possible to original, so bindings is more c-ish, then wrapper more d-ish.

**Comment by drug007** [comment]
Could  you tag it again because PR was accepted?

**Comment by SFrijters** [comment]
Done. Sorry for the extremely long delay...

**Comment by drug007** [comment]
Thanks!
